#Note: uncomment the below lines before configuring the properties. Key value should be used to configure secrets and its values
#apiVersion: v1
#kind: Secret
#metadata:
#  name: itaap-hyperautomation-nar-pricing-upload
#  namespace: {{deployNamespace}}
#data:
#  key: value