apiVersion: apps/v1
kind: Deployment
metadata:
  name: itaap-hyperautomation-nar-pricing-upload-deployment
  namespace: {{deployNamespace}}
  labels:
    app: itaap-hyperautomation-nar-pricing-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itaap-hyperautomation-nar-pricing-upload
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: itaap-hyperautomation-nar-pricing-upload
    spec:
      containers:
        - name: itaap-hyperautomation-nar-pricing-upload-container
          image: >-
            762168133611.dkr.ecr.eu-west-1.amazonaws.com/itaap/hyperautomation/itaap-hyperautomation-nar-pricing-upload:{{imageTagName}}

          ports:
            - containerPort: 8085
              protocol: TCP     
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: APP_VERSION
              value: {{appVersion}}
            - name: APP_ENV
              value: {{appEnv}}
            - name: AUDIT_CONNECTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: audit-connector-data
                  key: AUDIT_CONNECTOR_URL
            - name: AUDIT_CONNECTOR_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: audit-connector-data
                  key: AUDIT_CONNECTOR_USERNAME
            - name: AUDIT_CONNECTOR_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: audit-connector-data
                  key: AUDIT_CONNECTOR_PASSWORD
            - name: CW_EXPORT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cw-monitoring-secrets
                  key: cw.accessKye
            - name: CW_EXPORT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cw-monitoring-secrets
                  key: cw.secretKey
            - name: CW_EXPORT_REGION
              valueFrom:
                secretKeyRef:
                  name: cw-monitoring-secrets
                  key: cw.region
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
           requests:
             memory: "256Mi"
             cpu: "25m" 
           limits:
             memory: "512Mi"
             cpu: "100m"  
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64                        
      restartPolicy: Always
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---

apiVersion: v1
kind: Service
metadata:
  name: itaap-hyperautomation-nar-pricing-upload-service
  namespace: {{deployNamespace}}
  labels:
    app: itaap-hyperautomation-nar-pricing-upload
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  selector:
    app: itaap-hyperautomation-nar-pricing-upload











---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: itaap-hyperautomation-nar-pricing-upload-serviceaccount
  namespace: {{deployNamespace}}
  annotations:
    eks.amazonaws.com/role-arn: {{quoteCreationServiceAccountRoleArn}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itaap-hyperautomation-nar-pricing-upload-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://token-manage-service.itaap-{{env}}-common.svc.cluster.local/token/auth
    nginx.ingress.kubernetes.io/auth-response-headers: "authorization"
    nginx.ingress.kubernetes.io/auth-cache-key: '$http_authorization$request_uri'
    nginx.ingress.kubernetes.io/auth-cache-duration: '5m'
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{domainUrl}}
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  namespace: {{deployNamespace}}
spec:
  defaultBackend:
    service:
      name: itaap-hyperautomation-nar-pricing-upload-service
      port:
        number: 80
  tls:
    - hosts:
        - {{host}}
      secretName: itaap-tls-secret
  rules:
    - host: {{host}}
      http:
        paths:
          - path: {{envIdentifier}}/{{placeholder_from_user}}
            pathType: Prefix
            backend:
              service:
                name: itaap-hyperautomation-nar-pricing-upload-service
                port:
                  number: 80
