#Note: uncomment the below lines before configuring the properties. Key value should be used to configure properties and its values
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: itaap-hyperautomation-quote-creation-baseline-generation
#  namespace: {{deployNamespace}}
#data:
#  key: value
